### ISSUE TITLE
skip doesn't work properly

### ISSUE THREAD

**Issue by blankjude** [cpdt/mrvn-bot#1]

**Comment by cpdt** [comment]
Hey blankjude, thanks for reporting the issue. Can you please provide more details for what’s not working, what you would expect etc?

**Comment by blankjude** [comment]
Greetings, so I got up the bot and then added to the server. In the server `/play` command worked, when I try to skip it says that need two thumbsup to skip according to the config file, after reaching two thumbsup it seems to not be skipping still.

**Comment by cpdt** [comment]
Ah, it's not actually thumbsup based, you just need two people to use `/skip` to "vote" for skipping, e.g.:
![image](https://user-images.githubusercontent.com/16081865/133879596-efcb87da-fd08-49ea-9109-d498ef93a3b1.png)

I've just pushed a change to update the default message to hopefully make that more clear, so the bot will now say this:

![image](https://user-images.githubusercontent.com/16081865/133879716-9001b010-3806-4ede-974d-6e8cbe9a7a3f.png)

You'll need to update your config.json with the updated messages in config.example.json.

Does that seem fine to you?

**Comment by blankjude** [comment]
Just tested. Thanks, it seems working now. Closed.
